# This file is used for building and pushing images
services:
  node:
    build:
      context: .
      dockerfile: operator.Dockerfile
    image: ghcr.io/hydrogen-labs/anzen-avs/node:latest
  nodeplugin:
    build:
      context: .
      dockerfile: plugin.Dockerfile
    image: ghcr.io/hydrogen-labs/anzen-avs/nodeplugin:latest
